# Generated by Django 4.2.3 on 2023-07-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('comments', models.TextField(verbose_name='комментарии')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_time', models.DateTimeField(verbose_name='время рассылки')),
                ('periodicity', models.CharField(choices=[('раз в день', '@daily'), ('раз в неделю', '@weekly'), ('раз в месяц', '@monthly')], max_length=20, verbose_name='периодичность')),
                ('mail_status', models.CharField(max_length=50, verbose_name='статус отправки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.letter', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(auto_now=True, verbose_name='последняя отправка')),
                ('status', models.CharField(max_length=50, verbose_name='статус попытки')),
                ('server_answer', models.SmallIntegerField(blank=True, null=True, verbose_name='ответ сервера')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.letter', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
