# Generated by Django 4.2.3 on 2023-07-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.letter', verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='комментарии'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='mail_status',
            field=models.CharField(choices=[('создана', 'created'), ('запущена', 'running'), ('завершена', 'completed')], max_length=50, verbose_name='статус отправки'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='periodicity',
            field=models.CharField(choices=[('@daily', 'раз в день'), ('@weekly', 'раз в неделю'), ('@monthly', 'раз в месяц')], max_length=20, verbose_name='периодичность'),
        ),
    ]
