# Generated by Django 4.2.3 on 2023-07-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='получатели'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='mail_status',
            field=models.CharField(choices=[('создана', 'created'), ('запущена', 'running'), ('завершена', 'completed')], default='created', max_length=50, verbose_name='статус отправки'),
        ),
    ]
