# Generated by Django 4.2.3 on 2023-07-24 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_client_email_mailsettings_clients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='letter',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='mail_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 14, 0, 22, 728679), verbose_name='время рассылки'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_settings', to='mailing.letter', verbose_name='сообщение'),
        ),
    ]
