# Generated by Django 4.2.3 on 2023-07-24 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_remove_client_letter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsettings',
            name='mail_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время рассылки'),
        ),
    ]
