# Generated by Django 4.2.3 on 2023-07-29 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailsettings_mail_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailsettings',
            old_name='mail_time',
            new_name='mail_time_from',
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='mail_time_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время рассылки'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='mail_status',
            field=models.CharField(max_length=50, verbose_name='статус отправки'),
        ),
    ]
