# Generated by Django 4.2.3 on 2023-07-29 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_rename_mail_time_mailsettings_mail_time_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_time_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='рассылка с ')),
                ('mail_time_to', models.DateTimeField(default=django.utils.timezone.now, verbose_name='рассылка по')),
                ('periodicity', models.CharField(choices=[('@daily', 'раз в день'), ('@weekly', 'раз в неделю'), ('@monthly', 'раз в месяц')], max_length=20, verbose_name='периодичность')),
                ('mail_status', models.CharField(max_length=50, verbose_name='статус отправки')),
                ('clients', models.ManyToManyField(to='mailing.client', verbose_name='получатели')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.RenameModel(
            old_name='Letter',
            new_name='Message',
        ),
        migrations.DeleteModel(
            name='MailSettings',
        ),
        migrations.AddField(
            model_name='mail',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_settings', to='mailing.message', verbose_name='сообщение'),
        ),
    ]
