# Generated by Django 4.2.3 on 2023-07-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_mail_rename_letter_message_delete_mailsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='mail_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mailing.mail', verbose_name='рассылка'),
        ),
    ]
