# Generated by Django 4.2.3 on 2023-07-30 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_remove_logs_message_logs_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mail_settings',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='рассылка'),
            preserve_default=False,
        ),
    ]
