# Generated by Django 4.2.3 on 2023-08-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0016_client_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'permissions': [('set_status', 'Can set mail status')], 'verbose_name': 'настройка', 'verbose_name_plural': 'настройки'},
        ),
    ]
