# Generated by Django 4.2.3 on 2023-08-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0018_alter_logs_last_try'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'permissions': [('set_status', 'Can set mail status')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AddField(
            model_name='mail',
            name='last_send',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='последняя отправка'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=20, verbose_name='периодичность'),
        ),
    ]
